server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8

logback:
  logpath: @logback.logpath@
  name: @artifactId@

swagger:
  title: @project.artifactId@
  description: @project.description@
  version: @project.version@
  name: @swagger.user-name@
  email: @swagger.email@

dubbo:
  application:
    name: @project.artifactId@
  consumer:
    timeout: 6000
  protocol:
    name: dubbo
    port: 20810
  registry:
    address: N/A