server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8

logback:
  logpath: @logback.logpath@
  name: @artifactId@

swagger:
  title: @project.artifactId@
  description: @project.description@
  version: @project.version@
  name: @swagger.user-name@
  email: @swagger.email@

dubbo:
  application:
    name: @project.artifactId@
    logger: slf4j
  consumer:
    timeout: 6000
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://@nacos.host@:@nacos.port@
  service:
    version: 1.0.0

nacos:
  config:
    server-addr: @nacos.host@:@nacos.port@
    max-retry: 10 # 最大重试次数
    auto-refresh: false # 开启自动刷新
    config-retry-time: 2333 # 重试时间
    config-long-poll-timeout: 46000 # 配置监听长轮训超时时间
    namespace: 91481052-e652-49e9-9b02-1724e3dd6c23