server:
  port: 8040
  tomcat:
    uri-encoding: UTF-8

logback:
  logpath: @logback.logpath@
  app-name: @artifactId@

swagger:
  title: @project.artifactId@
  description: @project.description@
  version: @project.version@
  name: @swagger.user-name@
  email: @swagger.email@